from typing import ClassVar
from typing import Optional

from crewai_saas.schema.base import InDBBase, ResponseBase

#   public.llm (
#     id bigint generated by default as identity not null,
#     created_at timestamp without time zone not null default now(),
#     name character varying not null,
#     description text null,
#     detail text null,
#     is_popular boolean not null default false,
#     input_price numeric null,
#     output_price numeric null,
#     llm_provider_id bigint not null,
#     constraint llm_pkey primary key (id),
#     constraint llm_id_key unique (id),
#     constraint llm_llm_provider_id_fkey foreign key (llm_provider_id) references llm_provider (id)

class Llm(ResponseBase):
    name: str
    description: Optional[str] = ""
    detail: Optional[str] = ""
    is_popular: Optional[bool] = False
    input_price: Optional[float] = 0
    output_price: Optional[float] = 0
    llm_provider_id: int

    table_name: ClassVar[str] = "llm"

class LlmInDB(InDBBase):
    name: str
    description: Optional[str] = ""
    detail: Optional[str] = ""
    is_popular: Optional[bool] = False
    input_price: Optional[float] = 0
    output_price: Optional[float] = 0
    llm_provider_id: int

#   public.llm_provider (
#     id bigint generated by default as identity not null,
#     created_at timestamp with time zone not null default now(),
#     name character varying null,
#     constraint llm_provider_pkey primary key (id),
#     constraint llm_provider_id_key unique (id)

class LlmProvider(ResponseBase):
    name: Optional[str] = ""

    table_name: ClassVar[str] = "llm_provider"

class LlmProviderInDB(InDBBase):
    name: Optional[str] = ""

